import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarCompo from "@/components/SideBarCompo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        {children}
        {/* <div className="min-h-screen  md:w-1/5 bg-amber-400/10">
          <SideBarCompo />
        </div> */}
      </body>
    </html>
  );
}
